# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-deployment
# spec:
#   replicas: 10
#   selector:
#     matchLabels:
#       app: my-app
#   template:
#     metadata:
#       labels:
#         app: my-app
#     spec:
#       containers:
#         - name: my-container
#           image: heelercs/hiddenvillage-performancetest:latest
#           resources:
#             requests:
#               cpu: 0.2
#               memory: 100Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: loadtest
spec:
  parallelism: 20
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: heelercs/hiddenvillage-performancetest:latest
          name: loadtest
          command:
            - "npm"
            - "start"
            - "--"
            - "time=5m"
            - "fps=30"
          resources:
            requests:
              cpu: 0.2
              memory: 100Mi
      restartPolicy: Never
# ---------------
# command:
#   - bash
#   - -c
#   - |
#     set -eEuo pipefail
#     npm run start -- time=5m fps=30
#     npm run clean
# ---------------
# env:
#   - name: LOADTEST_DURATION
#     value: "120"

#   - name: LOADTEST_FPS
#     value: "30"
# ---------------
# CMD Commands Used:
# kubectl edit deployment my-deployment
# gcloud cheat-sheet
# kubectl get deployments
# kubectl delete deployments my-deployment
# kubectl config view
# kubectl apply -f manifest.yaml
# gcloud container clusters get-credentials autopilot-cluster-1 --zone=us-central1
# gcloud container clusters list
# kubectl create job loadtest --dry-run -o yaml --image=bob
# kubectl delete -f manifest.yaml && kubectl apply -f manifest.yaml && kubectl get jobs.batch,pods
# kubectl get pods -w
